### ISSUE TITLE
在运行指令时出现了未知错误

### ISSUE THREAD

**Issue by MuZhou233** [iTXTech/mirai-js#2]
## 环境
Windows 10 2004 一键安装包安装 Pure模式运行
## 描述
使用示例插件，可以启用，但执行禁用、卸载命令报错
```bash
jpm list
[0m 18:55:30 [INFO] [Command] 共加载了 1 个 MiraiJs 插件。
Id：0 文件：reply.js 名称：JsPluginExample 状态：启用 版本：1.0.0 作者：PeratX
[39;49mtps://github.com/iTXTech/mirai-js/blob/master/examples/reply.js
jpm disable JsPluginExample
[0m 18:55:43 [INFO] [Command] 在运行指令时出现了未知错误[39;49m
[0m 18:55:43 [INFO] [Mirai 0.5.2 Pkmon] java.lang.NumberFormatException: For input string: "JsPluginExample"
        at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.base/java.lang.Integer.parseInt(Unknown Source)
        at java.base/java.lang.Integer.parseInt(Unknown Source)
        at org.itxtech.miraijs.plugin.PluginManager$registerCommand$$inlined$registerCommand$lambda$1.invokeSuspend(PluginManager.kt:132)
        at org.itxtech.miraijs.plugin.PluginManager$registerCommand$$inlined$registerCommand$lambda$1.invoke(PluginManager.kt)
        at net.mamoe.mirai.console.command.AnonymousCommand.onCommand(Command.kt:122)
        at net.mamoe.mirai.console.command.CommandManager.processCommandImpl(CommandManager.kt:157)
        at net.mamoe.mirai.console.command.CommandManager$processCommand$2.invokeSuspend(CommandManager.kt:147)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
[39;49m
```

**Comment by PeratX** [comment]
`jpm`部分指令采用`plugin Id`来查找插件，故应为
`jpm disable 0` `jpm unload 0`
`jpm load xxx.js` `jpm info 0`
将会修改说明
