### ISSUE TITLE
未定义 JsonConfig

### ISSUE THREAD

**Issue by Talaxy009** [iTXTech/mirai-js#6]
使用Mirai-Js 1.2.1，`JsonConfig` 似乎用不了，一装载就出错，日志如下
```
2021-01-05 21:21:12 E/MiraiJs: Exception in coroutine Plugin MiraiJs of MiraiJs
org.mozilla.javascript.EcmaError: ReferenceError: "JsonConfig" is not defined. (miraiJs-tuling-bot.js#14)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4280)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4258)
        at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4348)
        at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1946)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1769)
        at script(miraiJs-tuling-bot.js:14)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy13.run(Unknown Source)
        at org.itxtech.miraijs.plugin.JsPlugin$load$1.invokeSuspend(JsPlugin.kt:110)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
代码相关部分如下
```js
let config = new JsonConfig(plugin.getDataFile("tulingBotConfig.json"));
```
求解QAQ

**Comment by PeratX** [comment]
新版本console可能移除了json config

**Comment by Talaxy009** [comment]
> 新版本console可能移除了json config

了解了😌，感谢解惑
